
services:
  mysql:
    container_name: mysqlReddit
    image: mysql
    environment:
      MYSQL_DATABASE: 'reddit-clone'              # name of database
      MYSQL_USER: 'admin'                # sample is the name of user
      MYSQL_PASSWORD: 'password'          # password for sample user
      MYSQL_ROOT_PASSWORD: 'password'     # password for root user
    volumes:
      - mysql-db:/var/lib/mysql
    ports:
      - '3307:3306'
    networks:
      - db
    restart: unless-stopped
    command: ["mysqld", "--mysql-native-password=ON"]

  phpmyadmin:
    container_name: phpmyadminReddit
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
    restart: unless-stopped
    ports:
      - "8081:80"
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  mysql-db: